# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

# optionally set up exclutions and allowed failures in the matrix
matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

before_script:
  - composer install
